apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-cias
  namespace: development
  labels:
    app: dev-cias
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: dev-cias
      tier: backend
  template:
    metadata:
      labels:
        app: dev-cias
        tier: backend
      annotations:
        armsPilotAutoEnable: "on"
        armsPilotCreateAppName: "dev-cias"
        armsAppType: PHP
    spec:
      containers:
      - name: dev-cias
        image: eros-acr-ee-registry-vpc.ap-southeast-5.cr.aliyuncs.com/dev-poc/cias:latest
        imagePullPolicy: Always
        resources: 
          limits:
            cpu: 60m
            memory: 240Mi
          requests:
            cpu: 30m
            memory: 120Mi
        ports:
        - containerPort: 8080
          name: dev-cias
        env:
        - name: MYSQL_HOST_NAME
          valueFrom:
            secretKeyRef:
              name: cias-mysql-secret
              key: host_name
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: cias-mysql-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cias-mysql-secret
              key: password
        - name: MYSQL_DB_NAME
          valueFrom:
            secretKeyRef:
              name: cias-mysql-secret
              key: db_name
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: cias-other-secret
              key: redis_host
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: cias-other-secret
              key: encryption_key
        volumeMounts:
        - mountPath: /etc/php7/conf.d/custom.ini
          name: php-ini
          subPath: php.ini
      imagePullSecrets:
      - name: acr-secret
      restartPolicy: Always
      volumes:
      - name: php-ini
        configMap:
          name: dev-cias-cm.ini